### PR TITLE
Dev1

### PR DESCRIPTION
**Pull request by sinkovit**
Hi Mary - I've made a few changes for you to review. The whole process was much easier than I expected.

(1) I forked a copy of your repo into my repository

(2) Made changes and committed to my repo

(3) Initiated the pull request. In this case I used my "dev1" branch, which was quite easy to do using the pull down menus at the top of the pull request page.

### CODE REVIEW

**Comment by sinkovit** [comment]
Mary - do me a favor and take away my permissions to directly edit your repo. I want to make sure that can see what it's like to be an outside collaborator.

**Comment by marypthomas** [comment]
Hi Bob -
I am learning about managing the repo. So, according to many places including here:
https://stackoverflow.com/questions/16250301/how-to-manage-collaborator-rights-in-github <https://stackoverflow.com/questions/16250301/how-to-manage-collaborator-rights-in-github>
You can either be added as a collaborator or you can be a contributor (default/public)
Collaborator privs depend on repo site type: if it is personal (like the one I created), all collaborators have R/W permissions.
If the repo is part of an organization  I can change collaborator roles and permissions.
So, I made the repo public, and I removed you as a collaborator.
Lets see what happens.
Mary

**Comment by marypthomas** [comment]
> Mary - do me a favor and take away my permissions to directly edit your repo. I want to make sure that can see what it's like to be an outside collaborator.

DONE.

**Comment by marypthomas** [comment]
Bob - I merged your pull request into the master.

**Comment by marypthomas** [comment]
https://www.lampsplus.com/products/danville-linen-shade-20-inch-wide-brushed-bronze-pendant-light__t8841.html <https://www.lampsplus.com/products/danville-linen-shade-20-inch-wide-brushed-bronze-pendant-light__t8841.html>

**Pull request merged**
